version: 2.1
jobs:
  deploy:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run:
          name: Installing pulumi
          command: |
            sudo apt-get update
            sudo apt-get install python3 python3-pip
            pip install -r requirements.txt
            curl -fsSL https://get.pulumi.com/ | sh
            pulumi login --non-interactive
            pulumi stack select dev
            pulumi up --yes
